[build]
  # cesta ku priečinku s frontendom (v tvojom prípade je to celý projekt Co_dom_dal)
  publish = "."
  # priečinok, kde sú funkcie (relatívne k tomuto netlify.toml)
  functions = "netlify/functions"

# --- Bezpečnostné a CSP hlavičky ---
[[headers]]
  for = "/*"
  [headers.values]
  # ✅ Povolené: vlastný web, Netlify domény, OpenAI API, Google Fonts
  Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.openai.com https://*.netlify.app https://*.netlify.live; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data:; script-src 'self' 'unsafe-inline';"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "0"

# --- (voliteľne) presmerovania pre fallback ---
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
